config/routes.rb
Rails.application.routes.draw do

  resources :bar_codes
  resources :qr_code_generators
  get 'qr_codes/new'

  get 'qr_codes/show'

  get 'qr_codes/create'

  resources :qr_codes, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar_code.rb
class BarCode < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bar_codes_controller.rb
class BarCodesController < ApplicationController
  before_action :set_bar_code, only: [:show, :edit, :update, :destroy]

  # GET /bar_codes
  # GET /bar_codes.json
  def index
    @bar_codes = BarCode.all
  end

  # GET /bar_codes/1
  # GET /bar_codes/1.json
  def show
  end

  # GET /bar_codes/new
  def new
    @bar_code = BarCode.new
  end

  # GET /bar_codes/1/edit
  def edit
  end

  # POST /bar_codes
  # POST /bar_codes.json
  def create
    @bar_code = BarCode.new(bar_code_params)
    gen = Barby::Code128B.new(@bar_code.text)
    send_data gen.to_png(:height => 50), :type => "image/png", :disposition => "inline"

    @bar_code.save



  end

  # PATCH/PUT /bar_codes/1
  # PATCH/PUT /bar_codes/1.json
  def update
    respond_to do |format|
      if @bar_code.update(bar_code_params)
        format.html { redirect_to @bar_code, notice: 'Bar code was successfully updated.' }
        format.json { render :show, status: :ok, location: @bar_code }
      else
        format.html { render :edit }
        format.json { render json: @bar_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bar_codes/1
  # DELETE /bar_codes/1.json
  def destroy
    @bar_code.destroy
    respond_to do |format|
      format.html { redirect_to bar_codes_url, notice: 'Bar code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar_code
      @bar_code = BarCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_code_params
      params.require(:bar_code).permit(:text)
    end
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def new

  end

  def create
    @qr = RQRCode::QRCode.new( qr_code_params[:text], size: 4)

  end



  private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_codes_helper.rb
module BarCodesHelper
end

app/helpers/qr_code_generators_helper.rb
module QrCodeGeneratorsHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/bar_codes/_form.html.erb
<%= form_with(model: bar_code, local: true) do |form| %>
  <% if bar_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bar_code.errors.count, "error") %> prohibited this bar_code from being saved:</h2>

      <ul>
      <% bar_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :bar_code_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bar_codes/edit.html.erb
<h1>Editing Bar Code</h1>

<%= render 'form', bar_code: @bar_code %>

<%= link_to 'Show', @bar_code %> |
<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bar Codes</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bar_codes.each do |bar_code| %>
      <tr>
        <td><%= bar_code.text %></td>
        <td><%= link_to 'Show', bar_code %></td>
        <td><%= link_to 'Edit', edit_bar_code_path(bar_code) %></td>
        <td><%= link_to 'Destroy', bar_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bar Code', new_bar_code_path %>

app/views/bar_codes/new.html.erb
<h1>New Bar Code</h1>

<%= render 'form', bar_code: @bar_code %>

<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @bar_code.text %>
</p>
<p>
  <br/>
</p>


<%= link_to 'Edit', edit_bar_code_path(@bar_code) %> |
<%= link_to 'Back', bar_codes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qr_codes/create.html.erb
<h1>QrCodes#create</h1>
<table class="qr-code">
  <% @qr.modules.each_index do |x| %>
      <tr>
        <% @qr.modules.each_index do |y| %>
            <% if @qr.dark?(x,y) %>
                <td class="black"/>
            <% else %>
                <td class="white"/>
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>
<br />
<br />
<%= link_to "New QR Code", new_qr_code_path %>

app/views/qr_codes/new.html.erb
<h1>QrCodes#new</h1>
<%= form_for :qr_code, url: qr_codes_path do |f| %>
    <%= f.label :text %>
    <%= f.text_field :text %>
    <%= f.submit %>
<% end %>